import { Question, UnmatchedAnswer, ExamDocument } from './types';

export const INITIAL_EXAM_DOCUMENT: ExamDocument = {
  questionPaperName: 'Class_10_maths_unit_test.pdf',
  questionPaperSize: '2MB',
  questionPaperPages: 2,
  answerSheetName: 'student_1_answer_sheet.pdf',
  answerSheetSize: '8MB',
  answerSheetPages: 4,
};

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'q1',
    number: '1',
    text: 'Which blood vessel carries blood away from the heart?',
    maxMarks: 2,
    scoredMarks: 2,
    status: 'correct',
    aiFeedback: 'Excellent work! Correctly identified arteries (specifically the aorta / pulmonary artery) as carrying blood away from the heart.',
    studentAnswerText: 'Q1. Arteries carry blood away from the heart. The largest artery carrying oxygenated blood is the aorta.',
    answerPages: [0],
    boundingBoxes: [
      {
        id: 'box-q1',
        pageIndex: 0,
        x: 5,
        y: 4,
        width: 90,
        height: 25,
        label: 'Q1',
      },
    ],
  },
  {
    id: 'q2',
    number: '2',
    text: 'Which of the following organelles is primarily involved in photosynthesis?',
    maxMarks: 2,
    scoredMarks: 2,
    status: 'correct',
    aiFeedback: 'Excellent work! You correctly identified the chloroplast as the organelle responsible for photosynthesis. Keep it up!',
    studentAnswerText: 'Q2. The process mainly occurs in the chloroplast of the plant cell. It has two main stages: 1. Light reaction - Captures light energy. 2. Dark reaction - Uses energy to make glucose.',
    answerPages: [0, 1], // Spans across page 1 and page 2
    boundingBoxes: [
      {
        id: 'box-q2-p1',
        pageIndex: 0,
        x: 5,
        y: 32,
        width: 90,
        height: 25,
        label: 'Q2',
      },
      {
        id: 'box-q2-p2',
        pageIndex: 1,
        x: 5,
        y: 80,
        width: 90,
        height: 15,
        label: 'Q2 (contd.)',
      },
    ],
  },
  {
    id: 'q3',
    number: '3',
    text: 'Explain the role of chloroplasts in photosynthesis, naming the main pigments involved and briefly outlining the two major stages of the process.',
    maxMarks: 2,
    scoredMarks: 2,
    status: 'correct',
    aiFeedback: 'Great explanation. Chlorophyll a and b mentioned correctly along with Light dependent reaction in thylakoids and Calvin cycle in stroma.',
    studentAnswerText: 'Q3. Chloroplasts contain chlorophyll pigment which absorbs solar energy. Light reaction occurs in thylakoid membranes, while dark reaction occurs in the stroma to form glucose.',
    answerPages: [0],
    boundingBoxes: [
      {
        id: 'box-q3',
        pageIndex: 0,
        x: 5,
        y: 60,
        width: 90,
        height: 33,
        label: 'Q3',
      },
    ],
  },
  {
    id: 'q4',
    number: '4',
    text: 'Describe the flow of blood through the human heart starting from the right atrium and ending at the aorta; include the names of valves crossed.',
    maxMarks: 2,
    scoredMarks: 0,
    status: 'unanswered',
    aiFeedback: 'Question was left unattempted by the student on the answer sheet. 0 out of 2 marks awarded.',
    studentAnswerText: '[Unanswered / No answer found on student answer sheet]',
    answerPages: [],
    boundingBoxes: [],
  },
  {
    id: 'q5',
    number: '5',
    text: 'Draw a labelled diagram of an alveolus showing capillaries and air space. Label alveolar sac, capillary, and direction of gas exchange.',
    maxMarks: 2,
    scoredMarks: 2,
    status: 'correct',
    isOutOfOrder: true,
    aiFeedback: 'Clear schematic diagram drawn with accurate labels for alveolar membrane, capillary wall, O2 entering blood and CO2 exiting.',
    studentAnswerText: 'Q5. [Diagram drawn] Alveolus structure with surrounding capillary network showing diffusion of O2 and CO2.',
    answerPages: [1],
    boundingBoxes: [
      {
        id: 'box-q5',
        pageIndex: 1,
        x: 5,
        y: 4,
        width: 90,
        height: 34,
        label: 'Q5',
      },
    ],
  },
  {
    id: 'q6',
    number: '6',
    text: 'Draw a neat labelled diagram of the human digestive system (stomach, small intestine, large intestine, liver, pancreas) and label the site where most absorption occurs.',
    maxMarks: 5,
    scoredMarks: 4,
    status: 'partial',
    aiFeedback: 'Diagram is neatly drawn and small intestine is correctly identified as the primary absorption site (villi). Minor omission: pancreas duct connection omitted.',
    studentAnswerText: 'Q6. Human Digestive System diagram. Small intestine labeled as the main site of nutrient absorption.',
    answerPages: [1],
    boundingBoxes: [
      {
        id: 'box-q6',
        pageIndex: 1,
        x: 5,
        y: 41,
        width: 90,
        height: 36,
        label: 'Q6',
      },
    ],
  },
  {
    id: 'q7',
    number: '7',
    text: 'Draw and label a nephron (Bowman\'s capsule, glomerulus, proximal tubule, loop of Henle, distal tubule, collecting duct).',
    maxMarks: 5,
    scoredMarks: 5,
    status: 'correct',
    aiFeedback: 'Flawless diagram! All 6 required anatomical components of the nephron are clearly drawn and labelled correctly.',
    studentAnswerText: 'Q7. Nephron structure diagram showing Bowman\'s capsule, glomerulus, renal tubule, and collecting duct.',
    answerPages: [2],
    boundingBoxes: [
      {
        id: 'box-q7',
        pageIndex: 2,
        x: 5,
        y: 4,
        width: 90,
        height: 40,
        label: 'Q7',
      },
    ],
  },
  {
    id: 'q8',
    number: '8',
    text: 'Explain the structural differences between palisade mesophyll and spongy mesophyll and state how each structure aids its function in the leaf.',
    maxMarks: 5,
    scoredMarks: 3,
    status: 'partial',
    aiFeedback: 'Correctly noted columnar packed palisade cells for light absorption. Spongy mesophyll air spaces mentioned but gas exchange surface area detail missing.',
    studentAnswerText: 'Q8. Palisade mesophyll has tightly packed vertical cells with high chlorophyll count for photosynthesis. Spongy mesophyll has loose air spaces for gas exchange.',
    answerPages: [2],
    boundingBoxes: [
      {
        id: 'box-q8',
        pageIndex: 2,
        x: 5,
        y: 47,
        width: 90,
        height: 33,
        label: 'Q8',
      },
    ],
  },
  {
    id: 'q9',
    number: '9',
    text: 'Describe the process of transpiration in plants in two to three sentences and name two environmental factors that increase its rate.',
    maxMarks: 5,
    scoredMarks: 5,
    status: 'correct',
    aiFeedback: 'Excellent! Transpiration defined as loss of water vapor via stomata creating suction pull. Temperature and wind speed correctly identified as factors.',
    studentAnswerText: 'Q9. Transpiration is the loss of water in the form of vapor from aerial parts of the plant through stomata. Factors increasing rate: 1. High temperature 2. Increased wind speed.',
    answerPages: [3],
    boundingBoxes: [
      {
        id: 'box-q9',
        pageIndex: 3,
        x: 5,
        y: 4,
        width: 90,
        height: 13,
        label: 'Q9',
      },
    ],
  },
  {
    id: 'q10',
    number: '10',
    text: 'Explain how the structure of xylem vessels facilitates water transport in plants (mention one structural feature and its role).',
    maxMarks: 5,
    scoredMarks: 4,
    status: 'partial',
    aiFeedback: 'Lignified walls mentioned preventing vessel collapse under tension. Could have also emphasized hollow continuous lumen with no end walls.',
    studentAnswerText: 'Q10. Xylem vessels have thick walls reinforced with lignin. This prevents vessel collapse when water is pulled upwards under high suction pressure.',
    answerPages: [3],
    boundingBoxes: [
      {
        id: 'box-q10',
        pageIndex: 3,
        x: 5,
        y: 18,
        width: 90,
        height: 13,
        label: 'Q10',
      },
    ],
  },
  {
    id: 'q11-a',
    number: '11 (a)',
    mainNumber: '11',
    subPart: 'a',
    text: 'A diagram shows two potted plants — Plant A in bright light with broad green leaves, Plant B kept in dim light with pale, elongated leaves.',
    maxMarks: 2,
    scoredMarks: 2,
    status: 'correct',
    aiFeedback: 'Identified etiolation in Plant B due to lack of sunlight, causing loss of chlorophyll (chlorosis) and stem elongation.',
    studentAnswerText: 'Q11 (a). Plant B shows etiolation because in dim light plants elongate stems to reach light and cannot synthesize chlorophyll efficiently.',
    answerPages: [3],
    boundingBoxes: [
      {
        id: 'box-q11-a',
        pageIndex: 3,
        x: 5,
        y: 32,
        width: 90,
        height: 14,
        label: 'Q11 (a)',
      },
    ],
  },
  {
    id: 'q11-b',
    number: '11 (b)',
    mainNumber: '11',
    subPart: 'b',
    text: 'Suggest one practical measure to help Plant B recover.',
    maxMarks: 3,
    scoredMarks: 1,
    status: 'partial',
    aiFeedback: 'Moving to sunlight suggested (1 mark). Missed providing adequate watering schedule and gradual light acclimatization details.',
    studentAnswerText: 'Q11 (b). Move Plant B back into direct sunlight location.',
    answerPages: [3],
    boundingBoxes: [
      {
        id: 'box-q11-b',
        pageIndex: 3,
        x: 5,
        y: 47,
        width: 90,
        height: 14,
        label: 'Q11 (b)',
      },
    ],
  },
  {
    id: 'q12',
    number: '12',
    text: 'A resting person has tidal volume (air per breath) of 0.5 L and breathes 12 times per minute.',
    maxMarks: 5,
    scoredMarks: 4,
    status: 'partial',
    aiFeedback: 'Total Minute Ventilation calculated correctly as 0.5 L * 12 = 6.0 L/min. Full step-by-step formula presentation slightly truncated.',
    studentAnswerText: 'Q12. Minute ventilation = Tidal Volume x Respiratory Rate = 0.5 L x 12 = 6 L/min.',
    answerPages: [3],
    boundingBoxes: [
      {
        id: 'box-q12',
        pageIndex: 3,
        x: 5,
        y: 62,
        width: 90,
        height: 14,
        label: 'Q12',
      },
    ],
  },
  {
    id: 'q13',
    number: '13',
    text: 'If dead space is 0.15 L per breath calculate the alveolar ventilation per minute. Show working.',
    maxMarks: 5,
    scoredMarks: 4,
    status: 'partial',
    aiFeedback: 'Alveolar ventilation = (0.5 - 0.15) * 12 = 4.2 L/min. Correct numerical result with working shown.',
    studentAnswerText: 'Q13. Alveolar ventilation = (Tidal volume - Dead space) x Rate = (0.5 - 0.15) L x 12 = 0.35 x 12 = 4.2 L/min.',
    answerPages: [3],
    boundingBoxes: [
      {
        id: 'box-q13',
        pageIndex: 3,
        x: 5,
        y: 77,
        width: 90,
        height: 14,
        label: 'Q13',
      },
    ],
  },
];

export const MOCK_UNMATCHED_ANSWERS: UnmatchedAnswer[] = [
  {
    id: 'unmatched-1',
    pageIndex: 2,
    boundingBox: {
      id: 'box-unmatched-1',
      pageIndex: 2,
      x: 5,
      y: 83,
      width: 90,
      height: 12,
      label: 'Unmatched Note',
    },
    transcript: 'Note: Photosynthetic Quotient PQ = CO2 evolved / O2 absorbed = 1.0 for carbohydrates.',
    note: 'This handwritten note on Page 3 does not correspond to any question prompt in the question paper.',
  },
];
